---
title: "Digital Trend Analyzer"
author: "Green Band"
date: '2018-12-16'
output:
  html_document:
    code_folding: hide
    toc_float: true
    toc: true
    toc_depth: 2
    theme: readable
    keep_md: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

# Step 0 : 분석 환경 설정

```{r, echo = F}

library(knitr)

library(latexpdf)

setwd("C:/Project/GreenBand_Lpoint5/Source/") ; getwd()

load(file="Code/R/Digital_Trend_Analyzer.RData")

```

```{r}

library(tidyverse) # Preprocessing, Visualizing

library(knitr) # Tidy document

library(ggrepel) # ggplot tidy text

```

# Step 1 : data pre-processing


# Step 2 : EDA

```{r}

summary(Product_original)

kable(head(Product_original), caption = 'Table1', align = 'c')

```









# Step 3 : Modeling

# Step 4 : Insight

# Step 5 : Proposal for New Service























```{r}


```


```{r, fig.cap = "Image1"}
plot(iris$Sepal.Length,iris$Petal.Length)
```

```{r, results = 'asis'}
kable(head(iris), caption = 'Table1', align = 'c')
```


*기울임*  
\*기울임*    
**굵게**  
**`형광펜`**  
~~지우기~~--이렇게 수정 

##### 1. list
  1. a;lskdfj
  + asdl;fk
      i) asfasf
      i) efsgsdg
        
##### box
    safasdfas  

## Quarterly Results {.tabset .tabset-fade .tabset-pills}

### By Product

(tab content)

### By Region

(tab content)

## Link
<http://rmarkdown.rstudio.com>

[name](http://rmarkdown.rstudio.com)